# Generated by Django 4.0 on 2021-12-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Intro to Comp Sci', 'Intro to Comp Sci'), ('Intro to Economics', 'Intro to Economics'), ('Deep Sea Underwater Basket Weaving', 'Deep Sea Underwater Basket Weaving')], max_length=60)),
                ('courseNumber', models.IntegerField()),
                ('instructorName', models.CharField(blank=True, default='', max_length=60)),
                ('duration', models.FloatField()),
            ],
        ),
    ]
